# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92bd1ddf96e2e9cc46f7e8b68ee13bdc3a33fce8f02ace27572e88d7c66bf56ffe34d3600ae56b28f7e76f0bef8b646d17c7ea5b27c607bd5d6e4e65625bfb25

test:
  secret_key_base: 1817afbdf7816bf7f106793280a6d7bbb9e602e0c7631e5ce7deb95f15a8f91ed048b0f1e99af50a341e2bf6bf87b4f482093107ba91dd9eb981d0e2672bb21f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
